<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
);





$url = 'private-page.php';
header("Location: {$url}", true, 302);
exit();